version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql-bookstore
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_PASSWORD: root
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"
